(*
  Copyright (c) 2026 Kevin Collins.

  This Source Code Form is subject to the terms of the Mozilla Public
  License, v. 2.0. If a copy of the MPL was not distributed with this
  file, You can obtain one at https://mozilla.org/MPL/2.0/.

  This Source Code Form is "Incompatible With Secondary Licenses",
  as defined by the Mozilla Public License, v. 2.0.

  SPDX-License-Identifier: MPL-2.0-no-copyleft-exception
*)

unit Lua55;

{$mode objfpc}{$H+}
{$PACKRECORDS C}

interface

uses
  ctypes;

const
  LUA_COLIBK = 4;
  LUA_DBLIBK = 8;
  LUA_ERRERR = 5;
  LUA_ERRFILE = 6;
  LUA_ERRMEM = 4;
  LUA_ERRRUN = 2;
  LUA_ERRSYNTAX = 3;
  LUA_GCCOLLECT = 2;
  LUA_GCCOUNT = 3;
  LUA_GCCOUNTB = 4;
  LUA_GCGEN = 7;
  LUA_GCINC = 8;
  LUA_GCISRUNNING = 6;
  LUA_GCPARAM = 9;
  LUA_GCPMAJORMINOR = 1;
  LUA_GCPMINORMAJOR = 2;
  LUA_GCPMINORMUL = 0;
  LUA_GCPN = 6;
  LUA_GCPPAUSE = 3;
  LUA_GCPSTEPMUL = 4;
  LUA_GCPSTEPSIZE = 5;
  LUA_GCRESTART = 1;
  LUA_GCSTEP = 5;
  LUA_GCSTOP = 0;
  LUA_GLIBK = 1;
  LUA_HOOKCALL = 0;
  LUA_HOOKCOUNT = 3;
  LUA_HOOKLINE = 2;
  LUA_HOOKRET = 1;
  LUA_HOOKTAILCALL = 4;
  LUA_IDSIZE = 60;
  LUA_IOLIBK = 16;
  LUA_LOADLIBK = 2;
  LUA_MASKCALL = 1;
  LUA_MASKCOUNT = 8;
  LUA_MASKLINE = 4;
  LUA_MASKRET = 2;
  LUA_MATHLIBK = 32;
  LUA_MINSTACK = 20;
  LUA_MULTRET = -1;
  LUA_N2SBUFFSZ = 64;
  LUA_NOREF = -2;
  LUA_NUMTYPES = 9;
  LUA_OK = 0;
  LUA_OPADD = 0;
  LUA_OPBAND = 7;
  LUA_OPBNOT = 13;
  LUA_OPBOR = 8;
  LUA_OPBXOR = 9;
  LUA_OPDIV = 5;
  LUA_OPEQ = 0;
  LUA_OPIDIV = 6;
  LUA_OPLE = 2;
  LUA_OPLT = 1;
  LUA_OPMOD = 3;
  LUA_OPMUL = 2;
  LUA_OPPOW = 4;
  LUA_OPSHL = 10;
  LUA_OPSHR = 11;
  LUA_OPSUB = 1;
  LUA_OPUNM = 12;
  LUA_OSLIBK = 64;
  LUA_REFNIL = -1;
  LUA_REGISTRYINDEX = -1073742823;
  LUA_RIDX_GLOBALS = 2;
  LUA_RIDX_LAST = 3;
  LUA_RIDX_MAINTHREAD = 3;
  LUA_STRLIBK = 128;
  LUA_TABLIBK = 256;
  LUA_TBOOLEAN = 1;
  LUA_TFUNCTION = 6;
  LUA_TLIGHTUSERDATA = 2;
  LUA_TNIL = 0;
  LUA_TNONE = -1;
  LUA_TNUMBER = 3;
  LUA_TSTRING = 4;
  LUA_TTABLE = 5;
  LUA_TTHREAD = 8;
  LUA_TUSERDATA = 7;
  LUA_UTF8LIBK = 512;
  LUA_VERSION_MAJOR_N = 5;
  LUA_VERSION_MINOR_N = 5;
  LUA_VERSION_NUM = 505;
  LUA_VERSION_RELEASE_N = 1;
  LUA_VERSION_RELEASE_NUM = 50501;
  LUA_YIELD = 1;
  LUA_VERSION_STRING = 'Lua 5.5';
  LUA_RELEASE = 'Lua 5.5.1';
  LUAL_BUFFERSIZE = 16 * SizeOf(Pointer) * 8;
  LUAL_NUMSIZES = 16 * 8 + 8;
  LUA_EXTRASPACE = SizeOf(Pointer);

type
  lua_State = record end;
  Plua_State = ^lua_State;
  PPlua_State = ^Plua_State;
  lua_Integer = Int64;
  Plua_Integer = ^lua_Integer;
  lua_Unsigned = QWord;
  Plua_Unsigned = ^lua_Unsigned;
  lua_Number = Double;
  Plua_Number = ^lua_Number;
  lua_KContext = PtrInt;
  PLuaCInt = ^cint;
  PLuaCUInt = ^cuint;
  PLuaCSize = ^SizeUInt;
  PPAnsiChar = ^PAnsiChar;
  PPPAnsiChar = ^PPAnsiChar;
  PFILE = Pointer;
  va_list = Pointer;
  Plua_Debug = ^lua_Debug;
  PluaL_Reg = ^luaL_Reg;
  PluaL_Buffer = ^luaL_Buffer;
  PluaL_Stream = ^luaL_Stream;
  lua_CFunction = function(L: Plua_State): cint; cdecl;
  lua_KFunction = function(L: Plua_State; AStatus: cint; ACtx: lua_KContext): cint; cdecl;
  lua_Reader = function(L: Plua_State; AUData: Pointer; ASize: PLuaCSize): PAnsiChar; cdecl;
  lua_Writer = function(L: Plua_State; AP: Pointer; ASize: SizeUInt; AUData: Pointer): cint; cdecl;
  lua_Alloc = function(AUData, APtr: Pointer; AOldSize, ANewSize: SizeUInt): Pointer; cdecl;
  lua_WarnFunction = procedure(AUData: Pointer; AMessage: PAnsiChar; AToContinue: cint); cdecl;
  lua_Hook = procedure(L: Plua_State; AAr: Plua_Debug); cdecl;
  lua_Debug = record
    event: cint;
    name, namewhat, what, source: PAnsiChar;
    srclen: SizeUInt;
    currentline, linedefined, lastlinedefined: cint;
    nups, nparams: Byte;
    isvararg: AnsiChar;
    extraargs: Byte;
    istailcall: AnsiChar;
    ftransfer, ntransfer: cint;
    short_src: array[0..LUA_IDSIZE-1] of AnsiChar;
    i_ci: Pointer;
  end;
  luaL_Reg = record
    name: PAnsiChar;
    func: lua_CFunction;
  end;
  TLuaBufferInit = record
    case Integer of
      0: (n: lua_Number);
      1: (u: Double);
      2: (s: Pointer);
      3: (i: lua_Integer);
      4: (l: CLong);
      5: (b: array[0..LUAL_BUFFERSIZE-1] of AnsiChar);
  end;
  luaL_Buffer = record
    b: PAnsiChar;
    size, n: SizeUInt;
    L: Plua_State;
    init: TLuaBufferInit;
  end;
  luaL_Stream = record
    f: PFILE;
    closef: lua_CFunction;
  end;

procedure luaL_addgsub(AArg1: PluaL_Buffer; AArg2: PAnsiChar; AArg3: PAnsiChar; AArg4: PAnsiChar); cdecl; external name 'luaL_addgsub';
procedure luaL_addlstring(AArg1: PluaL_Buffer; AArg2: PAnsiChar; AArg3: SizeUInt); cdecl; external name 'luaL_addlstring';
procedure luaL_addstring(AArg1: PluaL_Buffer; AArg2: PAnsiChar); cdecl; external name 'luaL_addstring';
procedure luaL_addvalue(AArg1: PluaL_Buffer); cdecl; external name 'luaL_addvalue';
function luaL_alloc(AArg1: Pointer; AArg2: Pointer; AArg3: SizeUInt; AArg4: SizeUInt): Pointer; cdecl; external name 'luaL_alloc';
function luaL_argerror(AArg1: Plua_State; AArg2: cint; AArg3: PAnsiChar): cint; cdecl; external name 'luaL_argerror';
procedure luaL_buffinit(AArg1: Plua_State; AArg2: PluaL_Buffer); cdecl; external name 'luaL_buffinit';
function luaL_buffinitsize(AArg1: Plua_State; AArg2: PluaL_Buffer; AArg3: SizeUInt): PAnsiChar; cdecl; external name 'luaL_buffinitsize';
function luaL_callmeta(AArg1: Plua_State; AArg2: cint; AArg3: PAnsiChar): cint; cdecl; external name 'luaL_callmeta';
procedure luaL_checkany(AArg1: Plua_State; AArg2: cint); cdecl; external name 'luaL_checkany';
function luaL_checkinteger(AArg1: Plua_State; AArg2: cint): lua_Integer; cdecl; external name 'luaL_checkinteger';
function luaL_checklstring(AArg1: Plua_State; AArg2: cint; AArg3: PLuaCSize): PAnsiChar; cdecl; external name 'luaL_checklstring';
function luaL_checknumber(AArg1: Plua_State; AArg2: cint): lua_Number; cdecl; external name 'luaL_checknumber';
function luaL_checkoption(AArg1: Plua_State; AArg2: cint; AArg3: PAnsiChar; AArg4: PPAnsiChar): cint; cdecl; external name 'luaL_checkoption';
procedure luaL_checkstack(AArg1: Plua_State; AArg2: cint; AArg3: PAnsiChar); cdecl; external name 'luaL_checkstack';
procedure luaL_checktype(AArg1: Plua_State; AArg2: cint; AArg3: cint); cdecl; external name 'luaL_checktype';
function luaL_checkudata(AArg1: Plua_State; AArg2: cint; AArg3: PAnsiChar): Pointer; cdecl; external name 'luaL_checkudata';
procedure luaL_checkversion_(AArg1: Plua_State; AArg2: lua_Number; AArg3: SizeUInt); cdecl; external name 'luaL_checkversion_';
function luaL_error(AArg1: Plua_State; AArg2: PAnsiChar): cint; cdecl; varargs; external name 'luaL_error';
function luaL_execresult(AArg1: Plua_State; AArg2: cint): cint; cdecl; external name 'luaL_execresult';
function luaL_fileresult(AArg1: Plua_State; AArg2: cint; AArg3: PAnsiChar): cint; cdecl; external name 'luaL_fileresult';
function luaL_getmetafield(AArg1: Plua_State; AArg2: cint; AArg3: PAnsiChar): cint; cdecl; external name 'luaL_getmetafield';
function luaL_getsubtable(AArg1: Plua_State; AArg2: cint; AArg3: PAnsiChar): cint; cdecl; external name 'luaL_getsubtable';
function luaL_gsub(AArg1: Plua_State; AArg2: PAnsiChar; AArg3: PAnsiChar; AArg4: PAnsiChar): PAnsiChar; cdecl; external name 'luaL_gsub';
function luaL_len(AArg1: Plua_State; AArg2: cint): lua_Integer; cdecl; external name 'luaL_len';
function luaL_loadbufferx(AArg1: Plua_State; AArg2: PAnsiChar; AArg3: SizeUInt; AArg4: PAnsiChar; AArg5: PAnsiChar): cint; cdecl; external name 'luaL_loadbufferx';
function luaL_loadfilex(AArg1: Plua_State; AArg2: PAnsiChar; AArg3: PAnsiChar): cint; cdecl; external name 'luaL_loadfilex';
function luaL_loadstring(AArg1: Plua_State; AArg2: PAnsiChar): cint; cdecl; external name 'luaL_loadstring';
function luaL_makeseed(AArg1: Plua_State): cuint; cdecl; external name 'luaL_makeseed';
function luaL_newmetatable(AArg1: Plua_State; AArg2: PAnsiChar): cint; cdecl; external name 'luaL_newmetatable';
function luaL_newstate: Plua_State; cdecl; external name 'luaL_newstate';
procedure luaL_openselectedlibs(AArg1: Plua_State; AArg2: cint; AArg3: cint); cdecl; external name 'luaL_openselectedlibs';
function luaL_optinteger(AArg1: Plua_State; AArg2: cint; AArg3: lua_Integer): lua_Integer; cdecl; external name 'luaL_optinteger';
function luaL_optlstring(AArg1: Plua_State; AArg2: cint; AArg3: PAnsiChar; AArg4: PLuaCSize): PAnsiChar; cdecl; external name 'luaL_optlstring';
function luaL_optnumber(AArg1: Plua_State; AArg2: cint; AArg3: lua_Number): lua_Number; cdecl; external name 'luaL_optnumber';
function luaL_prepbuffsize(AArg1: PluaL_Buffer; AArg2: SizeUInt): PAnsiChar; cdecl; external name 'luaL_prepbuffsize';
procedure luaL_pushresult(AArg1: PluaL_Buffer); cdecl; external name 'luaL_pushresult';
procedure luaL_pushresultsize(AArg1: PluaL_Buffer; AArg2: SizeUInt); cdecl; external name 'luaL_pushresultsize';
function luaL_ref(AArg1: Plua_State; AArg2: cint): cint; cdecl; external name 'luaL_ref';
procedure luaL_requiref(AArg1: Plua_State; AArg2: PAnsiChar; AArg3: lua_CFunction; AArg4: cint); cdecl; external name 'luaL_requiref';
procedure luaL_setfuncs(AArg1: Plua_State; AArg2: PluaL_Reg; AArg3: cint); cdecl; external name 'luaL_setfuncs';
procedure luaL_setmetatable(AArg1: Plua_State; AArg2: PAnsiChar); cdecl; external name 'luaL_setmetatable';
function luaL_testudata(AArg1: Plua_State; AArg2: cint; AArg3: PAnsiChar): Pointer; cdecl; external name 'luaL_testudata';
function luaL_tolstring(AArg1: Plua_State; AArg2: cint; AArg3: PLuaCSize): PAnsiChar; cdecl; external name 'luaL_tolstring';
procedure luaL_traceback(AArg1: Plua_State; AArg2: Plua_State; AArg3: PAnsiChar; AArg4: cint); cdecl; external name 'luaL_traceback';
function luaL_typeerror(AArg1: Plua_State; AArg2: cint; AArg3: PAnsiChar): cint; cdecl; external name 'luaL_typeerror';
procedure luaL_unref(AArg1: Plua_State; AArg2: cint; AArg3: cint); cdecl; external name 'luaL_unref';
procedure luaL_where(AArg1: Plua_State; AArg2: cint); cdecl; external name 'luaL_where';
function lua_absindex(AArg1: Plua_State; AArg2: cint): cint; cdecl; external name 'lua_absindex';
procedure lua_arith(AArg1: Plua_State; AArg2: cint); cdecl; external name 'lua_arith';
function lua_atpanic(AArg1: Plua_State; AArg2: lua_CFunction): lua_CFunction; cdecl; external name 'lua_atpanic';
procedure lua_callk(AArg1: Plua_State; AArg2: cint; AArg3: cint; AArg4: lua_KContext; AArg5: lua_KFunction); cdecl; external name 'lua_callk';
function lua_checkstack(AArg1: Plua_State; AArg2: cint): cint; cdecl; external name 'lua_checkstack';
procedure lua_close(AArg1: Plua_State); cdecl; external name 'lua_close';
procedure lua_closeslot(AArg1: Plua_State; AArg2: cint); cdecl; external name 'lua_closeslot';
function lua_closethread(AArg1: Plua_State; AArg2: Plua_State): cint; cdecl; external name 'lua_closethread';
function lua_compare(AArg1: Plua_State; AArg2: cint; AArg3: cint; AArg4: cint): cint; cdecl; external name 'lua_compare';
procedure lua_concat(AArg1: Plua_State; AArg2: cint); cdecl; external name 'lua_concat';
procedure lua_copy(AArg1: Plua_State; AArg2: cint; AArg3: cint); cdecl; external name 'lua_copy';
procedure lua_createtable(AArg1: Plua_State; AArg2: cint; AArg3: cint); cdecl; external name 'lua_createtable';
function lua_dump(AArg1: Plua_State; AArg2: lua_Writer; AArg3: Pointer; AArg4: cint): cint; cdecl; external name 'lua_dump';
function lua_error(AArg1: Plua_State): cint; cdecl; external name 'lua_error';
function lua_gc(AArg1: Plua_State; AArg2: cint): cint; cdecl; varargs; external name 'lua_gc';
function lua_getallocf(AArg1: Plua_State; AArg2: PPointer): lua_Alloc; cdecl; external name 'lua_getallocf';
function lua_getfield(AArg1: Plua_State; AArg2: cint; AArg3: PAnsiChar): cint; cdecl; external name 'lua_getfield';
function lua_getglobal(AArg1: Plua_State; AArg2: PAnsiChar): cint; cdecl; external name 'lua_getglobal';
function lua_gethook(AArg1: Plua_State): lua_Hook; cdecl; external name 'lua_gethook';
function lua_gethookcount(AArg1: Plua_State): cint; cdecl; external name 'lua_gethookcount';
function lua_gethookmask(AArg1: Plua_State): cint; cdecl; external name 'lua_gethookmask';
function lua_geti(AArg1: Plua_State; AArg2: cint; AArg3: lua_Integer): cint; cdecl; external name 'lua_geti';
function lua_getinfo(AArg1: Plua_State; AArg2: PAnsiChar; AArg3: Plua_Debug): cint; cdecl; external name 'lua_getinfo';
function lua_getiuservalue(AArg1: Plua_State; AArg2: cint; AArg3: cint): cint; cdecl; external name 'lua_getiuservalue';
function lua_getlocal(AArg1: Plua_State; AArg2: Plua_Debug; AArg3: cint): PAnsiChar; cdecl; external name 'lua_getlocal';
function lua_getmetatable(AArg1: Plua_State; AArg2: cint): cint; cdecl; external name 'lua_getmetatable';
function lua_getstack(AArg1: Plua_State; AArg2: cint; AArg3: Plua_Debug): cint; cdecl; external name 'lua_getstack';
function lua_gettable(AArg1: Plua_State; AArg2: cint): cint; cdecl; external name 'lua_gettable';
function lua_gettop(AArg1: Plua_State): cint; cdecl; external name 'lua_gettop';
function lua_getupvalue(AArg1: Plua_State; AArg2: cint; AArg3: cint): PAnsiChar; cdecl; external name 'lua_getupvalue';
function lua_iscfunction(AArg1: Plua_State; AArg2: cint): cint; cdecl; external name 'lua_iscfunction';
function lua_isinteger(AArg1: Plua_State; AArg2: cint): cint; cdecl; external name 'lua_isinteger';
function lua_isnumber(AArg1: Plua_State; AArg2: cint): cint; cdecl; external name 'lua_isnumber';
function lua_isstring(AArg1: Plua_State; AArg2: cint): cint; cdecl; external name 'lua_isstring';
function lua_isuserdata(AArg1: Plua_State; AArg2: cint): cint; cdecl; external name 'lua_isuserdata';
function lua_isyieldable(AArg1: Plua_State): cint; cdecl; external name 'lua_isyieldable';
procedure lua_len(AArg1: Plua_State; AArg2: cint); cdecl; external name 'lua_len';
function lua_load(AArg1: Plua_State; AArg2: lua_Reader; AArg3: Pointer; AArg4: PAnsiChar; AArg5: PAnsiChar): cint; cdecl; external name 'lua_load';
function lua_newstate(AArg1: lua_Alloc; AArg2: Pointer; AArg3: cuint): Plua_State; cdecl; external name 'lua_newstate';
function lua_newthread(AArg1: Plua_State): Plua_State; cdecl; external name 'lua_newthread';
function lua_newuserdatauv(AArg1: Plua_State; AArg2: SizeUInt; AArg3: cint): Pointer; cdecl; external name 'lua_newuserdatauv';
function lua_next(AArg1: Plua_State; AArg2: cint): cint; cdecl; external name 'lua_next';
function lua_numbertocstring(AArg1: Plua_State; AArg2: cint; AArg3: PAnsiChar): cuint; cdecl; external name 'lua_numbertocstring';
function lua_pcallk(AArg1: Plua_State; AArg2: cint; AArg3: cint; AArg4: cint; AArg5: lua_KContext; AArg6: lua_KFunction): cint; cdecl; external name 'lua_pcallk';
procedure lua_pushboolean(AArg1: Plua_State; AArg2: cint); cdecl; external name 'lua_pushboolean';
procedure lua_pushcclosure(AArg1: Plua_State; AArg2: lua_CFunction; AArg3: cint); cdecl; external name 'lua_pushcclosure';
function lua_pushexternalstring(AArg1: Plua_State; AArg2: PAnsiChar; AArg3: SizeUInt; AArg4: lua_Alloc; AArg5: Pointer): PAnsiChar; cdecl; external name 'lua_pushexternalstring';
function lua_pushfstring(AArg1: Plua_State; AArg2: PAnsiChar): PAnsiChar; cdecl; varargs; external name 'lua_pushfstring';
procedure lua_pushinteger(AArg1: Plua_State; AArg2: lua_Integer); cdecl; external name 'lua_pushinteger';
procedure lua_pushlightuserdata(AArg1: Plua_State; AArg2: Pointer); cdecl; external name 'lua_pushlightuserdata';
function lua_pushlstring(AArg1: Plua_State; AArg2: PAnsiChar; AArg3: SizeUInt): PAnsiChar; cdecl; external name 'lua_pushlstring';
procedure lua_pushnil(AArg1: Plua_State); cdecl; external name 'lua_pushnil';
procedure lua_pushnumber(AArg1: Plua_State; AArg2: lua_Number); cdecl; external name 'lua_pushnumber';
function lua_pushstring(AArg1: Plua_State; AArg2: PAnsiChar): PAnsiChar; cdecl; external name 'lua_pushstring';
function lua_pushthread(AArg1: Plua_State): cint; cdecl; external name 'lua_pushthread';
procedure lua_pushvalue(AArg1: Plua_State; AArg2: cint); cdecl; external name 'lua_pushvalue';
function lua_pushvfstring(AArg1: Plua_State; AArg2: PAnsiChar; AArg3: va_list): PAnsiChar; cdecl; external name 'lua_pushvfstring';
function lua_rawequal(AArg1: Plua_State; AArg2: cint; AArg3: cint): cint; cdecl; external name 'lua_rawequal';
function lua_rawget(AArg1: Plua_State; AArg2: cint): cint; cdecl; external name 'lua_rawget';
function lua_rawgeti(AArg1: Plua_State; AArg2: cint; AArg3: lua_Integer): cint; cdecl; external name 'lua_rawgeti';
function lua_rawgetp(AArg1: Plua_State; AArg2: cint; AArg3: Pointer): cint; cdecl; external name 'lua_rawgetp';
function lua_rawlen(AArg1: Plua_State; AArg2: cint): lua_Unsigned; cdecl; external name 'lua_rawlen';
procedure lua_rawset(AArg1: Plua_State; AArg2: cint); cdecl; external name 'lua_rawset';
procedure lua_rawseti(AArg1: Plua_State; AArg2: cint; AArg3: lua_Integer); cdecl; external name 'lua_rawseti';
procedure lua_rawsetp(AArg1: Plua_State; AArg2: cint; AArg3: Pointer); cdecl; external name 'lua_rawsetp';
function lua_resume(AArg1: Plua_State; AArg2: Plua_State; AArg3: cint; AArg4: PLuaCInt): cint; cdecl; external name 'lua_resume';
procedure lua_rotate(AArg1: Plua_State; AArg2: cint; AArg3: cint); cdecl; external name 'lua_rotate';
procedure lua_setallocf(AArg1: Plua_State; AArg2: lua_Alloc; AArg3: Pointer); cdecl; external name 'lua_setallocf';
procedure lua_setfield(AArg1: Plua_State; AArg2: cint; AArg3: PAnsiChar); cdecl; external name 'lua_setfield';
procedure lua_setglobal(AArg1: Plua_State; AArg2: PAnsiChar); cdecl; external name 'lua_setglobal';
procedure lua_sethook(AArg1: Plua_State; AArg2: lua_Hook; AArg3: cint; AArg4: cint); cdecl; external name 'lua_sethook';
procedure lua_seti(AArg1: Plua_State; AArg2: cint; AArg3: lua_Integer); cdecl; external name 'lua_seti';
function lua_setiuservalue(AArg1: Plua_State; AArg2: cint; AArg3: cint): cint; cdecl; external name 'lua_setiuservalue';
function lua_setlocal(AArg1: Plua_State; AArg2: Plua_Debug; AArg3: cint): PAnsiChar; cdecl; external name 'lua_setlocal';
function lua_setmetatable(AArg1: Plua_State; AArg2: cint): cint; cdecl; external name 'lua_setmetatable';
procedure lua_settable(AArg1: Plua_State; AArg2: cint); cdecl; external name 'lua_settable';
procedure lua_settop(AArg1: Plua_State; AArg2: cint); cdecl; external name 'lua_settop';
function lua_setupvalue(AArg1: Plua_State; AArg2: cint; AArg3: cint): PAnsiChar; cdecl; external name 'lua_setupvalue';
procedure lua_setwarnf(AArg1: Plua_State; AArg2: lua_WarnFunction; AArg3: Pointer); cdecl; external name 'lua_setwarnf';
function lua_status(AArg1: Plua_State): cint; cdecl; external name 'lua_status';
function lua_stringtonumber(AArg1: Plua_State; AArg2: PAnsiChar): SizeUInt; cdecl; external name 'lua_stringtonumber';
function lua_toboolean(AArg1: Plua_State; AArg2: cint): cint; cdecl; external name 'lua_toboolean';
function lua_tocfunction(AArg1: Plua_State; AArg2: cint): lua_CFunction; cdecl; external name 'lua_tocfunction';
procedure lua_toclose(AArg1: Plua_State; AArg2: cint); cdecl; external name 'lua_toclose';
function lua_tointegerx(AArg1: Plua_State; AArg2: cint; AArg3: PLuaCInt): lua_Integer; cdecl; external name 'lua_tointegerx';
function lua_tolstring(AArg1: Plua_State; AArg2: cint; AArg3: PLuaCSize): PAnsiChar; cdecl; external name 'lua_tolstring';
function lua_tonumberx(AArg1: Plua_State; AArg2: cint; AArg3: PLuaCInt): lua_Number; cdecl; external name 'lua_tonumberx';
function lua_topointer(AArg1: Plua_State; AArg2: cint): Pointer; cdecl; external name 'lua_topointer';
function lua_tothread(AArg1: Plua_State; AArg2: cint): Plua_State; cdecl; external name 'lua_tothread';
function lua_touserdata(AArg1: Plua_State; AArg2: cint): Pointer; cdecl; external name 'lua_touserdata';
function lua_type(AArg1: Plua_State; AArg2: cint): cint; cdecl; external name 'lua_type';
function lua_typename(AArg1: Plua_State; AArg2: cint): PAnsiChar; cdecl; external name 'lua_typename';
function lua_upvalueid(AArg1: Plua_State; AArg2: cint; AArg3: cint): Pointer; cdecl; external name 'lua_upvalueid';
procedure lua_upvaluejoin(AArg1: Plua_State; AArg2: cint; AArg3: cint; AArg4: cint; AArg5: cint); cdecl; external name 'lua_upvaluejoin';
function lua_version(AArg1: Plua_State): lua_Number; cdecl; external name 'lua_version';
procedure lua_warning(AArg1: Plua_State; AArg2: PAnsiChar; AArg3: cint); cdecl; external name 'lua_warning';
procedure lua_xmove(AArg1: Plua_State; AArg2: Plua_State; AArg3: cint); cdecl; external name 'lua_xmove';
function lua_yieldk(AArg1: Plua_State; AArg2: cint; AArg3: lua_KContext; AArg4: lua_KFunction): cint; cdecl; external name 'lua_yieldk';
function luaopen_base(AArg1: Plua_State): cint; cdecl; external name 'luaopen_base';
function luaopen_coroutine(AArg1: Plua_State): cint; cdecl; external name 'luaopen_coroutine';
function luaopen_debug(AArg1: Plua_State): cint; cdecl; external name 'luaopen_debug';
function luaopen_io(AArg1: Plua_State): cint; cdecl; external name 'luaopen_io';
function luaopen_math(AArg1: Plua_State): cint; cdecl; external name 'luaopen_math';
function luaopen_os(AArg1: Plua_State): cint; cdecl; external name 'luaopen_os';
function luaopen_package(AArg1: Plua_State): cint; cdecl; external name 'luaopen_package';
function luaopen_string(AArg1: Plua_State): cint; cdecl; external name 'luaopen_string';
function luaopen_table(AArg1: Plua_State): cint; cdecl; external name 'luaopen_table';
function luaopen_utf8(AArg1: Plua_State): cint; cdecl; external name 'luaopen_utf8';

function lua_upvalueindex(AIndex: cint): cint; inline;
procedure lua_pop(L: Plua_State; AN: cint); inline;
procedure lua_newtable(L: Plua_State); inline;
procedure lua_pushcfunction(L: Plua_State; AFunction: lua_CFunction); inline;
procedure lua_pushglobaltable(L: Plua_State); inline;
procedure lua_insert(L: Plua_State; AIndex: cint); inline;
procedure lua_remove(L: Plua_State; AIndex: cint); inline;
procedure lua_replace(L: Plua_State; AIndex: cint); inline;
function lua_tointeger(L: Plua_State; AIndex: cint): lua_Integer; inline;
function lua_tonumber(L: Plua_State; AIndex: cint): lua_Number; inline;
function lua_tostring(L: Plua_State; AIndex: cint): PAnsiChar; inline;
function lua_newuserdata(L: Plua_State; ASize: SizeUInt): Pointer; inline;
function lua_getuservalue(L: Plua_State; AIndex: cint): cint; inline;
function lua_setuservalue(L: Plua_State; AIndex: cint): cint; inline;
function lua_resetthread(L: Plua_State): cint; inline;
function lua_getextraspace(L: Plua_State): Pointer; inline;
function luaL_getmetatable(L: Plua_State; AName: PAnsiChar): cint; inline;
function luaL_loadfile(L: Plua_State; AFileName: PAnsiChar): cint; inline;
function luaL_loadbuffer(L: Plua_State; ABuffer: PAnsiChar; ASize: SizeUInt; AName: PAnsiChar): cint; inline;
function luaL_dofile(L: Plua_State; AFileName: PAnsiChar): cint; inline;
function luaL_dostring(L: Plua_State; ASource: PAnsiChar): cint; inline;
function luaL_checkstring(L: Plua_State; AArg: cint): PAnsiChar; inline;
function luaL_optstring(L: Plua_State; AArg: cint; ADefault: PAnsiChar): PAnsiChar; inline;
function luaL_typename(L: Plua_State; AIndex: cint): PAnsiChar; inline;
procedure luaL_checkversion(L: Plua_State); inline;
procedure luaL_openlibs(L: Plua_State); inline;
procedure luaL_pushfail(L: Plua_State); inline;
function luaL_bufflen(ABuffer: PluaL_Buffer): SizeUInt; inline;
function luaL_buffaddr(ABuffer: PluaL_Buffer): PAnsiChar; inline;
procedure luaL_addsize(ABuffer: PluaL_Buffer; ASize: SizeUInt); inline;
procedure luaL_buffsub(ABuffer: PluaL_Buffer; ASize: SizeUInt); inline;
function luaL_prepbuffer(ABuffer: PluaL_Buffer): PAnsiChar; inline;
procedure luaL_addchar(ABuffer: PluaL_Buffer; AChar: AnsiChar); inline;
procedure luaL_newlibtable(L: Plua_State; AFunctions: PluaL_Reg); inline;
procedure luaL_newlib(L: Plua_State; AFunctions: PluaL_Reg); inline;
procedure luaL_argcheck(L: Plua_State; ACondition: Boolean; AArg: cint; AMessage: PAnsiChar); inline;
procedure luaL_argexpected(L: Plua_State; ACondition: Boolean; AArg: cint; ATypeName: PAnsiChar); inline;

implementation

function lua_upvalueindex(AIndex: cint): cint; inline; begin Result := LUA_REGISTRYINDEX - AIndex; end;
procedure lua_pop(L: Plua_State; AN: cint); inline; begin lua_settop(L, -AN - 1); end;
procedure lua_newtable(L: Plua_State); inline; begin lua_createtable(L, 0, 0); end;
procedure lua_pushcfunction(L: Plua_State; AFunction: lua_CFunction); inline; begin lua_pushcclosure(L, AFunction, 0); end;
procedure lua_pushglobaltable(L: Plua_State); inline; begin lua_rawgeti(L, LUA_REGISTRYINDEX, LUA_RIDX_GLOBALS); end;
procedure lua_insert(L: Plua_State; AIndex: cint); inline; begin lua_rotate(L, AIndex, 1); end;
procedure lua_remove(L: Plua_State; AIndex: cint); inline; begin lua_rotate(L, AIndex, -1); lua_pop(L, 1); end;
procedure lua_replace(L: Plua_State; AIndex: cint); inline; begin lua_copy(L, -1, AIndex); lua_pop(L, 1); end;
function lua_tointeger(L: Plua_State; AIndex: cint): lua_Integer; inline; begin Result := lua_tointegerx(L, AIndex, nil); end;
function lua_tonumber(L: Plua_State; AIndex: cint): lua_Number; inline; begin Result := lua_tonumberx(L, AIndex, nil); end;
function lua_tostring(L: Plua_State; AIndex: cint): PAnsiChar; inline; begin Result := lua_tolstring(L, AIndex, nil); end;
function lua_newuserdata(L: Plua_State; ASize: SizeUInt): Pointer; inline; begin Result := lua_newuserdatauv(L, ASize, 1); end;
function lua_getuservalue(L: Plua_State; AIndex: cint): cint; inline; begin Result := lua_getiuservalue(L, AIndex, 1); end;
function lua_setuservalue(L: Plua_State; AIndex: cint): cint; inline; begin Result := lua_setiuservalue(L, AIndex, 1); end;
function lua_resetthread(L: Plua_State): cint; inline; begin Result := lua_closethread(L, nil); end;
function lua_getextraspace(L: Plua_State): Pointer; inline; begin Result := Pointer(PtrUInt(L) - LUA_EXTRASPACE); end;
function luaL_getmetatable(L: Plua_State; AName: PAnsiChar): cint; inline; begin Result := lua_getfield(L, LUA_REGISTRYINDEX, AName); end;
function luaL_loadfile(L: Plua_State; AFileName: PAnsiChar): cint; inline; begin Result := luaL_loadfilex(L, AFileName, nil); end;
function luaL_loadbuffer(L: Plua_State; ABuffer: PAnsiChar; ASize: SizeUInt; AName: PAnsiChar): cint; inline; begin Result := luaL_loadbufferx(L, ABuffer, ASize, AName, nil); end;
function luaL_dofile(L: Plua_State; AFileName: PAnsiChar): cint; inline; begin Result := luaL_loadfile(L, AFileName); if Result = LUA_OK then Result := lua_pcallk(L, 0, LUA_MULTRET, 0, 0, nil); end;
function luaL_dostring(L: Plua_State; ASource: PAnsiChar): cint; inline; begin Result := luaL_loadstring(L, ASource); if Result = LUA_OK then Result := lua_pcallk(L, 0, LUA_MULTRET, 0, 0, nil); end;
function luaL_checkstring(L: Plua_State; AArg: cint): PAnsiChar; inline; begin Result := luaL_checklstring(L, AArg, nil); end;
function luaL_optstring(L: Plua_State; AArg: cint; ADefault: PAnsiChar): PAnsiChar; inline; begin Result := luaL_optlstring(L, AArg, ADefault, nil); end;
function luaL_typename(L: Plua_State; AIndex: cint): PAnsiChar; inline; begin Result := lua_typename(L, lua_type(L, AIndex)); end;
procedure luaL_checkversion(L: Plua_State); inline; begin luaL_checkversion_(L, LUA_VERSION_NUM, LUAL_NUMSIZES); end;
procedure luaL_openlibs(L: Plua_State); inline; begin luaL_openselectedlibs(L, -1, 0); end;
procedure luaL_pushfail(L: Plua_State); inline; begin lua_pushnil(L); end;
function luaL_bufflen(ABuffer: PluaL_Buffer): SizeUInt; inline; begin Result := ABuffer^.n; end;
function luaL_buffaddr(ABuffer: PluaL_Buffer): PAnsiChar; inline; begin Result := ABuffer^.b; end;
procedure luaL_addsize(ABuffer: PluaL_Buffer; ASize: SizeUInt); inline; begin Inc(ABuffer^.n, ASize); end;
procedure luaL_buffsub(ABuffer: PluaL_Buffer; ASize: SizeUInt); inline; begin Dec(ABuffer^.n, ASize); end;
function luaL_prepbuffer(ABuffer: PluaL_Buffer): PAnsiChar; inline; begin Result := luaL_prepbuffsize(ABuffer, LUAL_BUFFERSIZE); end;
procedure luaL_addchar(ABuffer: PluaL_Buffer; AChar: AnsiChar); inline; begin if ABuffer^.n >= ABuffer^.size then luaL_prepbuffsize(ABuffer, 1); ABuffer^.b[ABuffer^.n] := AChar; Inc(ABuffer^.n); end;
procedure luaL_newlibtable(L: Plua_State; AFunctions: PluaL_Reg); inline; var lCount: cint; begin lCount := 0; while AFunctions[lCount].name <> nil do Inc(lCount); lua_createtable(L, 0, lCount); end;
procedure luaL_newlib(L: Plua_State; AFunctions: PluaL_Reg); inline; begin luaL_checkversion(L); luaL_newlibtable(L, AFunctions); luaL_setfuncs(L, AFunctions, 0); end;
procedure luaL_argcheck(L: Plua_State; ACondition: Boolean; AArg: cint; AMessage: PAnsiChar); inline; begin if not ACondition then luaL_argerror(L, AArg, AMessage); end;
procedure luaL_argexpected(L: Plua_State; ACondition: Boolean; AArg: cint; ATypeName: PAnsiChar); inline; begin if not ACondition then luaL_typeerror(L, AArg, ATypeName); end;
end.
